### ISSUE TITLE
No output when run demo

### ISSUE THREAD

**Issue by AIGirl10** [lqian/light-LPR#13]
When trying to run demo on x86, it is building successfully. But when trying to run it, it is not giving any output. The output vector is empty

```cpp
vector<PlateInfo> plateInfos = detector.recognize(img);
tm.stop();
printf("detect cost: %f (ms)\n", tm.getTimeMilli());
/* Printing vector size */
cout<<"\nsize:"<<plateInfos.size();
```
it is giving 0 as an output on [this](https://github.com/lqian/light-LPR/blob/master/images/20201005161220950.jpg) image

@lqian can you please check this ? Thank you !

**Comment by lqian** [comment]
It is missed detection for plate. Maybe the model has changed. or you can try a low threshold for PNet, RNet and ONet.

**Comment by AIGirl10** [comment]
@lqian 

Thank you so much for fast reply !

1. Tried to test on another image. [This one](https://drive.google.com/file/d/14aQGl3QwWo64sxUO8ePqlltWV-0C1BBb/view?usp=sharing)

and it gave this output.
```sh
plateNo: 粤WP9P
```

what can be the reason ?

2. When kept 0.4 as threshold for P, R and Onet it is still not giving any output (0 vector size).

I am using the original demo example given. in with Detect function is commented and calling recognize function.
```cpp
/*
 * mtcnn_test.cpp
 *
 *  Created on: Jun 25, 2019
 *      Author: lqian
 */

#include <opencv2/core.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>

#include <assert.h>
#include "mlpdr/MLPDR.h"

using namespace std;
using namespace mlpdr;
using namespace cv;
int main(int argc, char ** argv) {
        MLPDR detector(argv[1], 0.9f, 0.7f, 0.7f);
        Mat img = imread(argv[2]);
        assert(!img.empty());
        TickMeter tm;
        tm.start();
//      std::vector<mlpdr::PlateInfo> plateInfos = detector.Detect(img, 40, 3);  // 608.23 ms
        vector<PlateInfo> plateInfos = detector.recognize(img);
        tm.stop();
        printf("detect cost: %f (ms)\n", tm.getTimeMilli());
        cout<<"\nsize:"<<plateInfos.size();
        for (auto pi: plateInfos) {
                cout << "plateNo: " << pi.plateNo << endl;
        }
}
```

Please let me know if I am doing something wrong. Thank you !

**Comment by lqian** [comment]
please send picture which can be easy to access.

**Comment by lqian** [comment]
@AIGirl10 please try community branch code base.

**Comment by rsingh2083** [comment]
> When trying to run demo on x86, it is building successfully. But when trying to run it, it is not giving any output. The output vector is empty
> 
> ```c++
> vector<PlateInfo> plateInfos = detector.recognize(img);
> tm.stop();
> printf("detect cost: %f (ms)\n", tm.getTimeMilli());
> /* Printing vector size */
> cout<<"\nsize:"<<plateInfos.size();
> ```
> 
> it is giving 0 as an output on [this](https://github.com/lqian/light-LPR/blob/master/images/20201005161220950.jpg) image
> 
> @lqian can you please check this ? Thank you !

Hi,

I ran this `./examples/demo ../models/ ../images/20201005161220950.jpg` , but the only output Im getting is :-

```
initialized!
done ProposalNet with 60 proposal 
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
rnet run session and on copy to host
detect cost: 49654.972916 (ms)
```

Can anyone please help me

**Comment by lqian** [comment]
please try community branch source code.
