### ISSUE TITLE
How can I create a gui as shown in your demo video

### ISSUE THREAD

**Issue by rsingh2083** [lqian/light-LPR#15]
Hi,
![2021-03-10-001801_1920x1080_scrot](https://user-images.githubusercontent.com/5371252/110522069-84227580-8136-11eb-8794-5107061a803d.png)

I want to build a gui as was shown in your demo. Can you please share the source code of this gui ? 

Also please let me know which language/tech you have used for this GUI ?

**Comment by lqian** [comment]
it's the light-LPR-Tool, a commercial project relative with light-LPR.
