### ISSUE TITLE
实际测试效果不理想

### ISSUE THREAD

**Issue by yutaoxxx** [lqian/light-LPR#19]
大神您好！我尝试使用您这个结果，发现检测部分效果比较差，将检测换成效果更好的retinaFace之后，识别的效果还是很差。请问您这边开源的模型是否有所保留？

**Comment by lqian** [comment]
检测部分仍然是最早的mtcnn算法，有些网友反应在实际使用中很好。目前light-lpr已经走上商业化的方向，开源版本对于学习和研究车牌识别有一定的价值。
