### ISSUE TITLE
demo 跑起来 段错误

### ISSUE THREAD

**Issue by allenxcp** [lqian/light-LPR#6]
@lqian 
感谢作者开源，我在ubuntu16+opencv3.4上，运行作者的demo，用作者images文件夹里面提供的图片测试，检测不到车牌，或者段错误。请问有什么需要设置的吗？或者调整哪些参数？

**Comment by scutzhe** [comment]
我遇到同样的问题

**Comment by lqian** [comment]
杂事太多，没来得及修复，上周才修复好，请使用最新的community分之代码。
